events{}

http {
	server {
		# ---Basic setup---
		# Our server name must match our TLS key!
		server_name acastrov.42.fr;
		# We will listen to the port 443, as subject specifies (HTTPS default port)
		listen 443 ssl;

		# --TLS---
		# We should specify that we will be using TLS 1.2 and 1.3!
		ssl_protocols TLSv1.2 TLSv1.3;
		# The location of our certificates, as declared in the Docker file
		ssl_certificate /etc/nginx/ssl/inception.crt;
		ssl_certificate_key /etc/nginx/ssl/inception.key;

		# ---Wordpress---
		# Let's setup the basic Wordpress entry point in nginx
		root /var/www/html;
		index index.php index.html index.htm;

		# Let's try if there is a file or a folder, and return error =404 if not
		location / {
			try_files $uri $uri/ =404;
		}

		# Let's route all .php request through WordPress via port 9000 (WordPress default)
		#location ~ \.php$ {
		#	include snippets/fastcgi-php.conf;
		#	fastcgi_pass wordpress:9000;
		#}
	}
}